on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      TEAMSFX_ENV_NAME: 'test'
      CI_ENABLED: true

    steps:
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master

    - name: Setup Node 18.x
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'

    - name: install cli
      run: |
        npm install -g @microsoft/teamsfx-cli@2.0.2

    - name: Login Azure by service principal 
      run: |
        teamsfx account login azure --service-principal \
        -u ${{vars.AZURE_SERVICE_PRINCIPAL_NAME}}  \
        -p ${{secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD}} \
        --tenant ${{vars.AZURE_TENANT_ID}}

    - name: Deploy to hosting environment
      run: |
        teamsfx deploy --env ${{env.TEAMSFX_ENV_NAME}}

    - name: Package app
      run: |
        teamsfx package --env ${{env.TEAMSFX_ENV_NAME}}

    - name: upload zip
      uses: actions/upload-artifact@v2
      with:
        name: appPackage
        path: ./appPackage/build/appPackage.${{env.TEAMSFX_ENV_NAME}}.zip
