on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      TEAMSFX_ENV_NAME: 'test'
      CI_ENABLED: true

    steps:
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master

    - name: Setup Node 18.x
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'

    - name: install cli
      run: |
        npm install -g @microsoft/teamsfx-cli@2.0.2

    - name: 'zip artifact for deployment'
      run: |
        zip -r deploy.zip . 

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.cred }}

    - name: 'Run Azure webapp deploy action using azure RBAC'
      uses: azure/webapps-deploy@v2
      with:
        app-name: anonymousqf54baabot
        package: deploy.zip

    - name: Package app
      run: |
        teamsfx package --env ${{env.TEAMSFX_ENV_NAME}}

    - name: upload zip
      uses: actions/upload-artifact@v2
      with:
        name: appPackage
        path: ./appPackage/build/appPackage.${{env.TEAMSFX_ENV_NAME}}.zip
